"""empty message

Revision ID: 04789d6ba890
Revises: 20bc87756925
Create Date: 2020-09-16 02:31:10.046493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04789d6ba890'
down_revision = '20bc87756925'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('questions', sa.Text(), nullable=True),
    sa.Column('guess', sa.String(length=128), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessions')
    # ### end Alembic commands ###
