"""empty message

Revision ID: 9aadcc8a8fbe
Revises: a1acb2b77f3e
Create Date: 2020-09-13 01:34:23.262432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9aadcc8a8fbe'
down_revision = 'a1acb2b77f3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guess', sa.Column('picture', sa.Text(length=256), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guess', 'picture')
    # ### end Alembic commands ###
