"""empty message

Revision ID: a1acb2b77f3e
Revises: f6a46cba87a5
Create Date: 2020-09-13 00:16:02.391146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1acb2b77f3e'
down_revision = 'f6a46cba87a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guess',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guess', sa.String(length=128), nullable=True),
    sa.Column('questions', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('notice', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('questions')
    op.drop_table('guess')
    # ### end Alembic commands ###
