"""empty message

Revision ID: ade86997ea44
Revises: c2b8a2500c4e
Create Date: 2020-09-18 00:19:37.218800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ade86997ea44'
down_revision = 'c2b8a2500c4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('answers', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'answers')
    # ### end Alembic commands ###
