"""empty message

Revision ID: c2b8a2500c4e
Revises: 04789d6ba890
Create Date: 2020-09-17 22:07:20.676644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2b8a2500c4e'
down_revision = '04789d6ba890'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('accepted', sa.Integer(), nullable=False))
    op.add_column('sessions', sa.Column('found', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'found')
    op.drop_column('sessions', 'accepted')
    # ### end Alembic commands ###
